// ─── Geographic Reference Data ──────────────────────────────────
// Static lookup maps for countries, cities, US states, and continents.
// Extracted from location.ts to keep algorithmic logic separate from data.

// ─── Country Database ──────────────────────────────────────────
// Maps lowercase country names, abbreviations, and common variations
// to ISO 3166-1 alpha-2 codes.

export const COUNTRY_MAP: ReadonlyMap<string, string> = new Map([
  // ── A ──
  ["afghanistan", "AF"],
  ["albania", "AL"],
  ["algeria", "DZ"],
  ["argentina", "AR"],
  ["armenia", "AM"],
  ["australia", "AU"],
  ["austria", "AT"],
  ["azerbaijan", "AZ"],
  // ── B ──
  ["bahrain", "BH"],
  ["bangladesh", "BD"],
  ["belarus", "BY"],
  ["belgium", "BE"],
  ["bolivia", "BO"],
  ["bosnia", "BA"],
  ["bosnia and herzegovina", "BA"],
  ["brazil", "BR"],
  ["brasil", "BR"],
  ["brunei", "BN"],
  ["bulgaria", "BG"],
  // ── C ──
  ["cambodia", "KH"],
  ["cameroon", "CM"],
  ["canada", "CA"],
  ["chile", "CL"],
  ["china", "CN"],
  ["colombia", "CO"],
  ["costa rica", "CR"],
  ["croatia", "HR"],
  ["cuba", "CU"],
  ["cyprus", "CY"],
  ["czech republic", "CZ"],
  ["czechia", "CZ"],
  // ── D ──
  ["denmark", "DK"],
  ["dominican republic", "DO"],
  ["deutschland", "DE"],
  // ── E ──
  ["ecuador", "EC"],
  ["egypt", "EG"],
  ["el salvador", "SV"],
  ["england", "GB"],
  ["espana", "ES"],
  ["españa", "ES"],
  ["estonia", "EE"],
  ["ethiopia", "ET"],
  // ── F ──
  ["finland", "FI"],
  ["france", "FR"],
  // ── G ──
  ["georgia", "GE"],
  ["germany", "DE"],
  ["ghana", "GH"],
  ["greece", "GR"],
  ["guatemala", "GT"],
  // ── H ──
  ["honduras", "HN"],
  ["hong kong", "HK"],
  ["hungary", "HU"],
  // ── I ──
  ["iceland", "IS"],
  ["india", "IN"],
  ["indonesia", "ID"],
  ["iran", "IR"],
  ["iraq", "IQ"],
  ["ireland", "IE"],
  ["israel", "IL"],
  ["italy", "IT"],
  // ── J ──
  ["jamaica", "JM"],
  ["japan", "JP"],
  ["jordan", "JO"],
  // ── K ──
  ["kazakhstan", "KZ"],
  ["kenya", "KE"],
  ["korea", "KR"],
  ["south korea", "KR"],
  ["kuwait", "KW"],
  ["kyrgyzstan", "KG"],
  // ── L ──
  ["latvia", "LV"],
  ["lebanon", "LB"],
  ["libya", "LY"],
  ["lithuania", "LT"],
  ["luxembourg", "LU"],
  // ── M ──
  ["malaysia", "MY"],
  ["malta", "MT"],
  ["mexico", "MX"],
  ["méxico", "MX"],
  ["moldova", "MD"],
  ["mongolia", "MN"],
  ["montenegro", "ME"],
  ["morocco", "MA"],
  ["mozambique", "MZ"],
  ["myanmar", "MM"],
  // ── N ──
  ["nepal", "NP"],
  ["netherlands", "NL"],
  ["the netherlands", "NL"],
  ["holland", "NL"],
  ["new zealand", "NZ"],
  ["nigeria", "NG"],
  ["north macedonia", "MK"],
  ["norway", "NO"],
  // ── O ──
  ["oman", "OM"],
  // ── P ──
  ["pakistan", "PK"],
  ["palestine", "PS"],
  ["panama", "PA"],
  ["paraguay", "PY"],
  ["peru", "PE"],
  ["philippines", "PH"],
  ["poland", "PL"],
  ["portugal", "PT"],
  ["puerto rico", "PR"],
  // ── Q ──
  ["qatar", "QA"],
  // ── R ──
  ["romania", "RO"],
  ["russia", "RU"],
  ["rwanda", "RW"],
  // ── S ──
  ["saudi arabia", "SA"],
  ["scotland", "GB"],
  ["senegal", "SN"],
  ["serbia", "RS"],
  ["singapore", "SG"],
  ["slovakia", "SK"],
  ["slovenia", "SI"],
  ["south africa", "ZA"],
  ["spain", "ES"],
  ["sri lanka", "LK"],
  ["sudan", "SD"],
  ["sweden", "SE"],
  ["switzerland", "CH"],
  ["syria", "SY"],
  // ── T ──
  ["taiwan", "TW"],
  ["tanzania", "TZ"],
  ["thailand", "TH"],
  ["trinidad and tobago", "TT"],
  ["tunisia", "TN"],
  ["turkey", "TR"],
  ["türkiye", "TR"],
  ["turkiye", "TR"],
  // ── U ──
  ["uganda", "UG"],
  ["ukraine", "UA"],
  ["united arab emirates", "AE"],
  ["uae", "AE"],
  ["united kingdom", "GB"],
  ["united states", "US"],
  ["united states of america", "US"],
  ["uruguay", "UY"],
  ["uzbekistan", "UZ"],
  // ── V ──
  ["venezuela", "VE"],
  ["vietnam", "VN"],
  ["viet nam", "VN"],
  // ── W ──
  ["wales", "GB"],
  // ── Z ──
  ["zambia", "ZM"],
  ["zimbabwe", "ZW"],
  // ── Common abbreviations ──
  ["us", "US"],
  ["usa", "US"],
  ["u.s.", "US"],
  ["u.s.a.", "US"],
  ["uk", "GB"],
  ["u.k.", "GB"],
  ["gb", "GB"],
  ["de", "DE"],
  ["fr", "FR"],
  ["es", "ES"],
  ["it", "IT"],
  ["nl", "NL"],
  ["be", "BE"],
  ["at", "AT"],
  ["ch", "CH"],
  ["se", "SE"],
  ["no", "NO"],
  ["dk", "DK"],
  ["fi", "FI"],
  ["pl", "PL"],
  ["cz", "CZ"],
  ["pt", "PT"],
  ["ie", "IE"],
  ["ro", "RO"],
  ["hu", "HU"],
  ["bg", "BG"],
  ["hr", "HR"],
  ["sk", "SK"],
  ["si", "SI"],
  ["lt", "LT"],
  ["lv", "LV"],
  ["ee", "EE"],
  ["lu", "LU"],
  ["mt", "MT"],
  ["cy", "CY"],
  ["br", "BR"],
  ["ar", "AR"],
  ["mx", "MX"],
  ["co", "CO"],
  ["cl", "CL"],
  ["pe", "PE"],
  ["in", "IN"],
  ["cn", "CN"],
  ["jp", "JP"],
  ["kr", "KR"],
  ["tw", "TW"],
  ["sg", "SG"],
  ["hk", "HK"],
  ["my", "MY"],
  ["th", "TH"],
  ["id", "ID"],
  ["ph", "PH"],
  ["vn", "VN"],
  ["au", "AU"],
  ["nz", "NZ"],
  ["ca", "CA"],
  ["za", "ZA"],
  ["ng", "NG"],
  ["ke", "KE"],
  ["eg", "EG"],
  ["il", "IL"],
  ["tr", "TR"],
  ["ua", "UA"],
  ["ru", "RU"],
]);

// ─── US State Abbreviations ────────────────────────────────────
// Maps US state abbreviations and full names to "US".

export const US_STATES: ReadonlyMap<string, string> = new Map([
  ["al", "US"],
  ["alabama", "US"],
  ["ak", "US"],
  ["alaska", "US"],
  ["az", "US"],
  ["arizona", "US"],
  ["ar", "US"],
  ["arkansas", "US"],
  ["co", "US"],
  ["colorado", "US"],
  ["ct", "US"],
  ["connecticut", "US"],
  ["dc", "US"],
  ["district of columbia", "US"],
  ["fl", "US"],
  ["florida", "US"],
  ["ga", "US"],
  ["georgia (us)", "US"],
  ["hi", "US"],
  ["hawaii", "US"],
  ["id", "US"],
  ["idaho", "US"],
  ["il", "US"],
  ["illinois", "US"],
  ["ia", "US"],
  ["iowa", "US"],
  ["ks", "US"],
  ["kansas", "US"],
  ["ky", "US"],
  ["kentucky", "US"],
  ["la", "US"],
  ["louisiana", "US"],
  ["me", "US"],
  ["maine", "US"],
  ["md", "US"],
  ["maryland", "US"],
  ["ma", "US"],
  ["massachusetts", "US"],
  ["mi", "US"],
  ["michigan", "US"],
  ["mn", "US"],
  ["minnesota", "US"],
  ["ms", "US"],
  ["mississippi", "US"],
  ["mo", "US"],
  ["missouri", "US"],
  ["mt", "US"],
  ["montana", "US"],
  ["ne", "US"],
  ["nebraska", "US"],
  ["nv", "US"],
  ["nevada", "US"],
  ["nh", "US"],
  ["new hampshire", "US"],
  ["nj", "US"],
  ["new jersey", "US"],
  ["nm", "US"],
  ["new mexico", "US"],
  ["ny", "US"],
  ["new york state", "US"],
  ["nc", "US"],
  ["north carolina", "US"],
  ["nd", "US"],
  ["north dakota", "US"],
  ["oh", "US"],
  ["ohio", "US"],
  ["ok", "US"],
  ["oklahoma", "US"],
  ["or", "US"],
  ["oregon", "US"],
  ["pa", "US"],
  ["pennsylvania", "US"],
  ["ri", "US"],
  ["rhode island", "US"],
  ["sc", "US"],
  ["south carolina", "US"],
  ["sd", "US"],
  ["south dakota", "US"],
  ["tn", "US"],
  ["tennessee", "US"],
  ["tx", "US"],
  ["texas", "US"],
  ["ut", "US"],
  ["utah", "US"],
  ["vt", "US"],
  ["vermont", "US"],
  ["va", "US"],
  ["virginia", "US"],
  ["wa", "US"],
  ["washington state", "US"],
  ["wv", "US"],
  ["west virginia", "US"],
  ["wi", "US"],
  ["wisconsin", "US"],
  ["wy", "US"],
  ["wyoming", "US"],
  // "ca" and "in" intentionally omitted — ambiguous with Canada/India
  ["california", "US"],
  ["indiana", "US"],
]);

// ─── City Database ─────────────────────────────────────────────
// Maps lowercase city names (+ common abbreviations) to country codes.
// Focused on major tech hubs and frequently used GitHub locations.

export const CITY_MAP: ReadonlyMap<string, { countryCode: string; canonical: string }> = new Map([
  // ── North America ──
  ["san francisco", { countryCode: "US", canonical: "san francisco" }],
  ["sf", { countryCode: "US", canonical: "san francisco" }],
  ["san francisco bay area", { countryCode: "US", canonical: "san francisco" }],
  ["sf bay area", { countryCode: "US", canonical: "san francisco" }],
  ["bay area", { countryCode: "US", canonical: "san francisco" }],
  ["silicon valley", { countryCode: "US", canonical: "san francisco" }],
  ["new york", { countryCode: "US", canonical: "new york" }],
  ["new york city", { countryCode: "US", canonical: "new york" }],
  ["nyc", { countryCode: "US", canonical: "new york" }],
  ["brooklyn", { countryCode: "US", canonical: "new york" }],
  ["manhattan", { countryCode: "US", canonical: "new york" }],
  ["los angeles", { countryCode: "US", canonical: "los angeles" }],
  ["la", { countryCode: "US", canonical: "los angeles" }],
  ["seattle", { countryCode: "US", canonical: "seattle" }],
  ["austin", { countryCode: "US", canonical: "austin" }],
  ["boston", { countryCode: "US", canonical: "boston" }],
  ["chicago", { countryCode: "US", canonical: "chicago" }],
  ["denver", { countryCode: "US", canonical: "denver" }],
  ["portland", { countryCode: "US", canonical: "portland" }],
  ["atlanta", { countryCode: "US", canonical: "atlanta" }],
  ["miami", { countryCode: "US", canonical: "miami" }],
  ["dallas", { countryCode: "US", canonical: "dallas" }],
  ["houston", { countryCode: "US", canonical: "houston" }],
  ["san diego", { countryCode: "US", canonical: "san diego" }],
  ["san jose", { countryCode: "US", canonical: "san jose" }],
  ["philadelphia", { countryCode: "US", canonical: "philadelphia" }],
  ["phoenix", { countryCode: "US", canonical: "phoenix" }],
  ["minneapolis", { countryCode: "US", canonical: "minneapolis" }],
  ["detroit", { countryCode: "US", canonical: "detroit" }],
  ["raleigh", { countryCode: "US", canonical: "raleigh" }],
  ["durham", { countryCode: "US", canonical: "durham" }],
  ["research triangle", { countryCode: "US", canonical: "raleigh" }],
  ["washington", { countryCode: "US", canonical: "washington" }],
  ["washington dc", { countryCode: "US", canonical: "washington" }],
  ["dc", { countryCode: "US", canonical: "washington" }],
  ["pittsburgh", { countryCode: "US", canonical: "pittsburgh" }],
  ["salt lake city", { countryCode: "US", canonical: "salt lake city" }],
  ["nashville", { countryCode: "US", canonical: "nashville" }],
  // Canada
  ["toronto", { countryCode: "CA", canonical: "toronto" }],
  ["vancouver", { countryCode: "CA", canonical: "vancouver" }],
  ["montreal", { countryCode: "CA", canonical: "montreal" }],
  ["montréal", { countryCode: "CA", canonical: "montreal" }],
  ["ottawa", { countryCode: "CA", canonical: "ottawa" }],
  ["calgary", { countryCode: "CA", canonical: "calgary" }],
  ["waterloo", { countryCode: "CA", canonical: "waterloo" }],
  // Mexico
  ["mexico city", { countryCode: "MX", canonical: "mexico city" }],
  ["cdmx", { countryCode: "MX", canonical: "mexico city" }],
  ["guadalajara", { countryCode: "MX", canonical: "guadalajara" }],
  ["monterrey", { countryCode: "MX", canonical: "monterrey" }],
  // ── South America ──
  ["são paulo", { countryCode: "BR", canonical: "sao paulo" }],
  ["sao paulo", { countryCode: "BR", canonical: "sao paulo" }],
  ["rio de janeiro", { countryCode: "BR", canonical: "rio de janeiro" }],
  ["buenos aires", { countryCode: "AR", canonical: "buenos aires" }],
  ["bogota", { countryCode: "CO", canonical: "bogota" }],
  ["bogotá", { countryCode: "CO", canonical: "bogota" }],
  ["lima", { countryCode: "PE", canonical: "lima" }],
  ["santiago", { countryCode: "CL", canonical: "santiago" }],
  ["medellin", { countryCode: "CO", canonical: "medellin" }],
  ["medellín", { countryCode: "CO", canonical: "medellin" }],
  // ── Europe ──
  ["london", { countryCode: "GB", canonical: "london" }],
  ["manchester", { countryCode: "GB", canonical: "manchester" }],
  ["birmingham", { countryCode: "GB", canonical: "birmingham" }],
  ["edinburgh", { countryCode: "GB", canonical: "edinburgh" }],
  ["bristol", { countryCode: "GB", canonical: "bristol" }],
  ["cambridge", { countryCode: "GB", canonical: "cambridge" }],
  ["oxford", { countryCode: "GB", canonical: "oxford" }],
  ["paris", { countryCode: "FR", canonical: "paris" }],
  ["lyon", { countryCode: "FR", canonical: "lyon" }],
  ["marseille", { countryCode: "FR", canonical: "marseille" }],
  ["toulouse", { countryCode: "FR", canonical: "toulouse" }],
  ["nantes", { countryCode: "FR", canonical: "nantes" }],
  ["berlin", { countryCode: "DE", canonical: "berlin" }],
  ["munich", { countryCode: "DE", canonical: "munich" }],
  ["münchen", { countryCode: "DE", canonical: "munich" }],
  ["hamburg", { countryCode: "DE", canonical: "hamburg" }],
  ["frankfurt", { countryCode: "DE", canonical: "frankfurt" }],
  ["cologne", { countryCode: "DE", canonical: "cologne" }],
  ["köln", { countryCode: "DE", canonical: "cologne" }],
  ["düsseldorf", { countryCode: "DE", canonical: "dusseldorf" }],
  ["stuttgart", { countryCode: "DE", canonical: "stuttgart" }],
  ["amsterdam", { countryCode: "NL", canonical: "amsterdam" }],
  ["rotterdam", { countryCode: "NL", canonical: "rotterdam" }],
  ["the hague", { countryCode: "NL", canonical: "the hague" }],
  ["eindhoven", { countryCode: "NL", canonical: "eindhoven" }],
  ["madrid", { countryCode: "ES", canonical: "madrid" }],
  ["barcelona", { countryCode: "ES", canonical: "barcelona" }],
  ["valencia", { countryCode: "ES", canonical: "valencia" }],
  ["rome", { countryCode: "IT", canonical: "rome" }],
  ["roma", { countryCode: "IT", canonical: "rome" }],
  ["milan", { countryCode: "IT", canonical: "milan" }],
  ["milano", { countryCode: "IT", canonical: "milan" }],
  ["lisbon", { countryCode: "PT", canonical: "lisbon" }],
  ["lisboa", { countryCode: "PT", canonical: "lisbon" }],
  ["porto", { countryCode: "PT", canonical: "porto" }],
  ["dublin", { countryCode: "IE", canonical: "dublin" }],
  ["zurich", { countryCode: "CH", canonical: "zurich" }],
  ["zürich", { countryCode: "CH", canonical: "zurich" }],
  ["geneva", { countryCode: "CH", canonical: "geneva" }],
  ["bern", { countryCode: "CH", canonical: "bern" }],
  ["vienna", { countryCode: "AT", canonical: "vienna" }],
  ["wien", { countryCode: "AT", canonical: "vienna" }],
  ["copenhagen", { countryCode: "DK", canonical: "copenhagen" }],
  ["stockholm", { countryCode: "SE", canonical: "stockholm" }],
  ["gothenburg", { countryCode: "SE", canonical: "gothenburg" }],
  ["oslo", { countryCode: "NO", canonical: "oslo" }],
  ["helsinki", { countryCode: "FI", canonical: "helsinki" }],
  ["warsaw", { countryCode: "PL", canonical: "warsaw" }],
  ["krakow", { countryCode: "PL", canonical: "krakow" }],
  ["kraków", { countryCode: "PL", canonical: "krakow" }],
  ["wroclaw", { countryCode: "PL", canonical: "wroclaw" }],
  ["prague", { countryCode: "CZ", canonical: "prague" }],
  ["praha", { countryCode: "CZ", canonical: "prague" }],
  ["budapest", { countryCode: "HU", canonical: "budapest" }],
  ["bucharest", { countryCode: "RO", canonical: "bucharest" }],
  ["bucuresti", { countryCode: "RO", canonical: "bucharest" }],
  ["sofia", { countryCode: "BG", canonical: "sofia" }],
  ["tallinn", { countryCode: "EE", canonical: "tallinn" }],
  ["riga", { countryCode: "LV", canonical: "riga" }],
  ["vilnius", { countryCode: "LT", canonical: "vilnius" }],
  ["bratislava", { countryCode: "SK", canonical: "bratislava" }],
  ["ljubljana", { countryCode: "SI", canonical: "ljubljana" }],
  ["zagreb", { countryCode: "HR", canonical: "zagreb" }],
  ["belgrade", { countryCode: "RS", canonical: "belgrade" }],
  ["kyiv", { countryCode: "UA", canonical: "kyiv" }],
  ["kiev", { countryCode: "UA", canonical: "kyiv" }],
  ["moscow", { countryCode: "RU", canonical: "moscow" }],
  ["saint petersburg", { countryCode: "RU", canonical: "saint petersburg" }],
  ["st petersburg", { countryCode: "RU", canonical: "saint petersburg" }],
  ["istanbul", { countryCode: "TR", canonical: "istanbul" }],
  ["ankara", { countryCode: "TR", canonical: "ankara" }],
  // ── Asia ──
  ["tokyo", { countryCode: "JP", canonical: "tokyo" }],
  ["osaka", { countryCode: "JP", canonical: "osaka" }],
  ["kyoto", { countryCode: "JP", canonical: "kyoto" }],
  ["yokohama", { countryCode: "JP", canonical: "yokohama" }],
  ["fukuoka", { countryCode: "JP", canonical: "fukuoka" }],
  ["seoul", { countryCode: "KR", canonical: "seoul" }],
  ["busan", { countryCode: "KR", canonical: "busan" }],
  ["beijing", { countryCode: "CN", canonical: "beijing" }],
  ["shanghai", { countryCode: "CN", canonical: "shanghai" }],
  ["shenzhen", { countryCode: "CN", canonical: "shenzhen" }],
  ["hangzhou", { countryCode: "CN", canonical: "hangzhou" }],
  ["guangzhou", { countryCode: "CN", canonical: "guangzhou" }],
  ["chengdu", { countryCode: "CN", canonical: "chengdu" }],
  ["taipei", { countryCode: "TW", canonical: "taipei" }],
  ["bangalore", { countryCode: "IN", canonical: "bangalore" }],
  ["bengaluru", { countryCode: "IN", canonical: "bangalore" }],
  ["mumbai", { countryCode: "IN", canonical: "mumbai" }],
  ["bombay", { countryCode: "IN", canonical: "mumbai" }],
  ["delhi", { countryCode: "IN", canonical: "delhi" }],
  ["new delhi", { countryCode: "IN", canonical: "delhi" }],
  ["hyderabad", { countryCode: "IN", canonical: "hyderabad" }],
  ["chennai", { countryCode: "IN", canonical: "chennai" }],
  ["pune", { countryCode: "IN", canonical: "pune" }],
  ["kolkata", { countryCode: "IN", canonical: "kolkata" }],
  ["ahmedabad", { countryCode: "IN", canonical: "ahmedabad" }],
  ["noida", { countryCode: "IN", canonical: "noida" }],
  ["gurgaon", { countryCode: "IN", canonical: "gurgaon" }],
  ["gurugram", { countryCode: "IN", canonical: "gurgaon" }],
  ["singapore", { countryCode: "SG", canonical: "singapore" }],
  ["kuala lumpur", { countryCode: "MY", canonical: "kuala lumpur" }],
  ["kl", { countryCode: "MY", canonical: "kuala lumpur" }],
  ["bangkok", { countryCode: "TH", canonical: "bangkok" }],
  ["jakarta", { countryCode: "ID", canonical: "jakarta" }],
  ["ho chi minh city", { countryCode: "VN", canonical: "ho chi minh city" }],
  ["hanoi", { countryCode: "VN", canonical: "hanoi" }],
  ["manila", { countryCode: "PH", canonical: "manila" }],
  ["dhaka", { countryCode: "BD", canonical: "dhaka" }],
  ["karachi", { countryCode: "PK", canonical: "karachi" }],
  ["lahore", { countryCode: "PK", canonical: "lahore" }],
  ["islamabad", { countryCode: "PK", canonical: "islamabad" }],
  // ── Middle East ──
  ["tel aviv", { countryCode: "IL", canonical: "tel aviv" }],
  ["jerusalem", { countryCode: "IL", canonical: "jerusalem" }],
  ["dubai", { countryCode: "AE", canonical: "dubai" }],
  ["abu dhabi", { countryCode: "AE", canonical: "abu dhabi" }],
  ["riyadh", { countryCode: "SA", canonical: "riyadh" }],
  ["doha", { countryCode: "QA", canonical: "doha" }],
  // ── Africa ──
  ["lagos", { countryCode: "NG", canonical: "lagos" }],
  ["nairobi", { countryCode: "KE", canonical: "nairobi" }],
  ["cape town", { countryCode: "ZA", canonical: "cape town" }],
  ["johannesburg", { countryCode: "ZA", canonical: "johannesburg" }],
  ["cairo", { countryCode: "EG", canonical: "cairo" }],
  ["accra", { countryCode: "GH", canonical: "accra" }],
  ["addis ababa", { countryCode: "ET", canonical: "addis ababa" }],
  ["casablanca", { countryCode: "MA", canonical: "casablanca" }],
  ["tunis", { countryCode: "TN", canonical: "tunis" }],
  // ── Oceania ──
  ["sydney", { countryCode: "AU", canonical: "sydney" }],
  ["melbourne", { countryCode: "AU", canonical: "melbourne" }],
  ["brisbane", { countryCode: "AU", canonical: "brisbane" }],
  ["perth", { countryCode: "AU", canonical: "perth" }],
  ["adelaide", { countryCode: "AU", canonical: "adelaide" }],
  ["auckland", { countryCode: "NZ", canonical: "auckland" }],
  ["wellington", { countryCode: "NZ", canonical: "wellington" }],
]);

// ─── Continent Groupings ───────────────────────────────────────
// Maps ISO alpha-2 country codes to continent identifiers.

export const CONTINENT_MAP: ReadonlyMap<string, string> = new Map([
  // North America
  ...["US", "CA", "MX", "GT", "HN", "SV", "CR", "PA", "CU", "JM", "DO", "PR", "TT"].map(
    (c) => [c, "NA"] as const
  ),
  // South America
  ...["BR", "AR", "CL", "CO", "PE", "VE", "EC", "BO", "PY", "UY"].map((c) => [c, "SA"] as const),
  // Europe
  ...[
    "GB",
    "FR",
    "DE",
    "ES",
    "IT",
    "NL",
    "BE",
    "AT",
    "CH",
    "SE",
    "NO",
    "DK",
    "FI",
    "PL",
    "CZ",
    "PT",
    "IE",
    "RO",
    "HU",
    "BG",
    "HR",
    "SK",
    "SI",
    "LT",
    "LV",
    "EE",
    "LU",
    "MT",
    "CY",
    "RS",
    "BA",
    "ME",
    "MK",
    "AL",
    "MD",
    "UA",
    "BY",
    "IS",
  ].map((c) => [c, "EU"] as const),
  // Asia
  ...[
    "JP",
    "KR",
    "CN",
    "TW",
    "HK",
    "SG",
    "MY",
    "TH",
    "ID",
    "PH",
    "VN",
    "KH",
    "MM",
    "IN",
    "BD",
    "PK",
    "LK",
    "NP",
    "KZ",
    "KG",
    "UZ",
    "MN",
    "BN",
    "IL",
    "TR",
    "AE",
    "SA",
    "QA",
    "BH",
    "KW",
    "OM",
    "JO",
    "LB",
    "IQ",
    "IR",
    "SY",
    "GE",
    "AM",
    "AZ",
    "PS",
  ].map((c) => [c, "AS"] as const),
  // Russia spans both — classify as Europe for proximity purposes
  ["RU", "EU"],
  // Africa
  ...[
    "NG",
    "KE",
    "ZA",
    "EG",
    "GH",
    "ET",
    "TZ",
    "UG",
    "RW",
    "SN",
    "CM",
    "MA",
    "DZ",
    "TN",
    "LY",
    "SD",
    "MZ",
    "ZM",
    "ZW",
  ].map((c) => [c, "AF"] as const),
  // Oceania
  ...["AU", "NZ"].map((c) => [c, "OC"] as const),
]);

// ─── Non-Geographic Terms ──────────────────────────────────────
// Strings people put in their GitHub location that have no geographic meaning.

export const NON_GEOGRAPHIC = new Set([
  "remote",
  "worldwide",
  "earth",
  "global",
  "internet",
  "the internet",
  "cyberspace",
  "cloud",
  "everywhere",
  "anywhere",
  "nomad",
  "digital nomad",
  "home",
  "space",
  "mars",
  "moon",
  "universe",
  "localhost",
  "127.0.0.1",
  "/dev/null",
  "null",
  "undefined",
  "n/a",
  "none",
  "somewhere",
  "here",
  "there",
  "around",
  "world",
  "the world",
]);
