import { DAY_MS, DAYS_PER_WEEK } from "./time";

export const INVITE_CODE_ALPHABET = "ABCDEFGHJKMNPQRSTUVWXYZ23456789";
export const INVITE_CODE_LENGTH = 8;
export const MAX_INVITE_CODES_PER_USER = 3;
export const STACK_SCORE_POINTS_PER_REFERRAL = 5;
export const INVITE_BONUS_MAX_SCORE = MAX_INVITE_CODES_PER_USER * STACK_SCORE_POINTS_PER_REFERRAL;
export const EARLY_ACCESS_INVITE_TOKEN_PREFIX = "inv_";
export const EARLY_ACCESS_INVITE_TOKEN_TTL_MS = DAYS_PER_WEEK * DAY_MS;
