import { DAY_MS, SECOND_MS } from "@stackmatch/constants/time";

export const PACKAGE_PREVIEW_COUNT = 5;
export const OWNER_PREVIEW_COUNT = 5;
export const OWNER_BLURRED_COUNT = 4;

export const MATCH_PREVIEW_COUNT = 3;
export const MATCH_CARD_TOP_STACK_LIMIT = 3;
export const MATCH_CARD_MOBILE_TOP_STACK_LIMIT = 2;
export const OWNER_MATCH_CANDIDATE_LIMIT = 150;
export const OWNER_MATCH_CACHE_TTL_MS = DAY_MS;
export const OWNER_MATCH_CACHE_WARM_BATCH_LIMIT = 25;
export const OWNER_MATCH_CACHE_WARM_HOUR_UTC = 6;
export const OWNER_MATCH_CACHE_WARM_MINUTE_UTC = 45;
export const OWNER_PAGE_DATA_CACHE_TTL_MS = DAY_MS;
export const OWNER_PAGE_SERVER_DATA_CACHE_REVALIDATE_SECONDS = 60;
export const OWNER_PAGE_DATA_CACHE_WARM_BATCH_LIMIT = 25;
export const OWNER_PAGE_DATA_CACHE_WARM_HOUR_UTC = 7;
export const OWNER_PAGE_DATA_CACHE_WARM_MINUTE_UTC = 0;
export const OWNER_PAGE_QUERY_SLOW_MS = SECOND_MS;
export const BLURRED_TEASER_COUNT = 3;
export const OWNERS_GRID_CARD_LIMIT = 12;
export const FEED_RECENT_WINDOW_DAYS = 14;
export const OWNER_PAGE_RECENT_STARS_LIMIT = 10;
export const OWNER_PAGE_PUBLIC_REPOS_PREVIEW_LIMIT = 4;
export const OWNER_PAGE_TOP_PUBLIC_REPOS_LIMIT = 10;

export const FEED_RECENT_WINDOW_MS = FEED_RECENT_WINDOW_DAYS * DAY_MS;
