/**
 * Centralized route definitions for Stackmatch.
 * Always use these constants instead of hardcoded strings for navigation.
 */
export const ROUTES = {
  home: "/",
  login: "/login",
  about: "/about",
  docs: {
    home: "/docs",
    ranks: "/docs/ranks",
    attribution: "/docs/attribution",
  },
  legal: {
    privacy: "/privacy",
    terms: "/terms",
    contact: "/contact",
    unsubscribe: "/unsubscribe",
  },
  settings: {
    home: "/settings",
    account: "/settings/account",
    notifications: "/settings/notifications",
  },
  admin: {
    home: "/admin",
    audit: "/admin/audit",
    moderation: "/admin/moderation",
    profiles: "/admin/profiles",
    security: "/admin/security",
  },
  notifications: "/notifications",
  feed: "/feed",
  messages: "/messages",
  companies: "/companies",
  sponsors: "/sponsors",
  developers: "/developers",
  stacks: "/stacks",
  topics: "/topics",
  topStackers: "/top-stackers",
  ranks: "/ranks",
  leaderboard: {
    home: "/leaderboard",
    stacks: "/leaderboard/stacks",
    developers: "/leaderboard/developers",
    repos: "/leaderboard/repos",
    aiTools: "/leaderboard/ai-tools",
    bots: "/leaderboard/bots",
    skills: "/leaderboard/skills",
  },
  waitlistReferral: (code: string) => `/r/${encodeURIComponent(code)}`,
  invite: (code: string) => `/invite/${code}`,
  owner: (owner: string) => `/${encodeURIComponent(owner)}`,
  repo: (owner: string, repo: string) =>
    `/${encodeURIComponent(owner)}/${encodeURIComponent(repo)}`,
  package: (name: string) => `/package/${encodeURIComponent(name)}`,
  language: (lang: string) => `/language/${encodeURIComponent(lang)}`,
  topic: (topic: string) => `/topic/${encodeURIComponent(topic)}`,
  external: {
    github: (owner: string, repo?: string) =>
      `https://github.com/${owner}${repo ? `/${repo}` : ""}`,
    githubAvatar: (owner: string, size = 120) => `https://github.com/${owner}.png?size=${size}`,
    twitter: (text: string, url: string) =>
      `https://twitter.com/intent/tweet?text=${encodeURIComponent(text)}&url=${encodeURIComponent(url)}`,
    npm: (packageName: string) => `https://www.npmjs.com/package/${packageName}`,
    jsDelivrPackage: (packageName: string) => `https://www.jsdelivr.com/package/npm/${packageName}`,
    stackOverflowTag: (tag: string) =>
      `https://stackoverflow.com/questions/tagged/${encodeURIComponent(tag)}`,
    librariesIoPackage: (packageName: string) =>
      `https://libraries.io/npm/${encodeURIComponent(packageName)}`,
    skills: (query: string) => `https://skills.sh/?q=${encodeURIComponent(query)}`,
    sponsor: "https://github.com/sponsors/thedaviddias",
    aiTools: {
      githubCopilot: "https://github.com/features/copilot",
      claudeCode: "https://docs.anthropic.com/en/docs/agents-and-tools/claude-code/overview",
      cursor: "https://cursor.com",
      aider: "https://aider.chat",
      devin: "https://devin.ai",
      openaiCodex: "https://openai.com/index/codex-cli",
      gemini: "https://gemini.google.com",
      amazonQ: "https://aws.amazon.com/q/developer",
      sweep: "https://sweep.dev",
      coderabbit: "https://coderabbit.ai",
      seerBySentry: "https://sentry.io",
      qodoMerge: "https://www.qodo.ai",
      greptile: "https://greptile.com",
      korbitAi: "https://korbit.ai",
      codeium: "https://codeium.com",
      windsurf: "https://windsurf.com",
      sourcegraphCody: "https://sourcegraph.com/cody",
      tabnine: "https://tabnine.com",
      continueDev: "https://continue.dev",
      replitAgent: "https://replit.com",
      bolt: "https://bolt.new",
      v0: "https://v0.dev",
      blackboxAi: "https://blackbox.ai",
      lovable: "https://lovable.dev",
    },
    botTools: {
      dependabot: "https://github.com/dependabot",
      renovate: "https://docs.renovatebot.com",
      githubActions: "https://github.com/features/actions",
      semanticRelease: "https://semantic-release.gitbook.io",
      snykBot: "https://snyk.io",
      sentryBot: "https://sentry.io",
      codecov: "https://codecov.io",
      sonarcloud: "https://sonarcloud.io",
      greenkeeper: "https://greenkeeper.io",
      imgbot: "https://imgbot.net",
      allContributors: "https://allcontributors.org",
      releasePlease: "https://github.com/googleapis/release-please",
      mergify: "https://mergify.com",
      vercel: "https://vercel.com",
      netlify: "https://netlify.com",
      changesets: "https://github.com/changesets/changesets",
      kodiak: "https://kodiakhq.com",
      expoBot: "https://expo.dev",
      weblate: "https://weblate.org",
      googleJules: "https://jules.google.com",
    },
  },
  api: {
    github: {
      user: (owner: string) => `https://api.github.com/users/${owner}`,
    },
    og: {
      user: (owner: string) => `/api/og/user?owner=${encodeURIComponent(owner)}`,
      repo: (owner: string, name: string) =>
        `/api/og/repo?owner=${encodeURIComponent(owner)}&name=${encodeURIComponent(name)}`,
      package: (name: string) => `/api/og/package?name=${encodeURIComponent(name)}`,
    },
  },
} as const;
