export type AttributionClassification =
  | "human"
  | "dependabot"
  | "renovate"
  | "copilot"
  | "claude"
  | "cursor"
  | "aider"
  | "devin"
  | "openai-codex"
  | "gemini"
  | "github-actions"
  | "other-bot"
  | "ai-assisted";

interface PatternSources {
  login?: RegExp[];
  coAuthor?: RegExp[];
  message?: RegExp[];
  prBody?: RegExp[];
  prBranch?: RegExp[];
  detailed?: RegExp[];
}

interface AiReviewAgentMapping {
  key: string;
  label: string;
  classification: AttributionClassification;
  sources: PatternSources;
}

interface PatternClassification {
  pattern: RegExp;
  classification: AttributionClassification;
}

interface DetailedPatternMatch {
  pattern: RegExp;
  match: { key: string; label: string };
}

const AI_REVIEW_AGENT_MAPPINGS: AiReviewAgentMapping[] = [
  {
    key: "coderabbit",
    label: "CodeRabbit",
    classification: "ai-assisted",
    sources: {
      login: [/coderabbitai/i, /coderabbit(?:\[bot\])?/i],
      coAuthor: [/coderabbitai/i, /coderabbit/i],
      message: [/Generated by CodeRabbit/i],
      prBody: [/Generated by CodeRabbit/i],
      prBranch: [/^coderabbit\//i],
      detailed: [/coderabbit(?:ai)?(?:\[bot\])?/i],
    },
  },
  {
    key: "seer-by-sentry",
    label: "Seer by Sentry",
    classification: "ai-assisted",
    sources: {
      login: [/seer-by-sentry(?:\[bot\])?/i, /sentry-ai-review(?:er)?(?:\[bot\])?/i],
      coAuthor: [/seer-by-sentry/i, /sentry-ai-review(?:er)?/i],
      message: [/Generated by Seer/i, /seer-by-sentry/i, /sentry-ai-review(?:er)?/i],
      prBody: [/Generated by Seer/i, /seer-by-sentry/i, /sentry-ai-review(?:er)?/i],
      prBranch: [/^seer(?:-by-sentry)?\//i],
      detailed: [/seer-by-sentry(?:\[bot\])?/i, /sentry-ai-review(?:er)?(?:\[bot\])?/i],
    },
  },
  {
    key: "qodo-merge",
    label: "Qodo Merge",
    classification: "ai-assisted",
    sources: {
      login: [/qodo-merge(?:-pro)?(?:\[bot\])?/i],
      coAuthor: [/qodo(?:-merge)?/i],
      message: [/Generated by Qodo/i],
      prBody: [/Generated by Qodo/i],
      prBranch: [/^qodo(?:-merge)?\//i],
      detailed: [/qodo(?:-merge(?:-pro)?)?(?:\[bot\])?/i],
    },
  },
  {
    key: "greptile",
    label: "Greptile",
    classification: "ai-assisted",
    sources: {
      login: [/greptile(?:-apps)?(?:\[bot\])?/i],
      coAuthor: [/greptile/i],
      message: [/Generated by Greptile/i],
      prBody: [/Generated by Greptile/i],
      prBranch: [/^greptile\//i],
      detailed: [/greptile(?:-apps)?(?:\[bot\])?/i],
    },
  },
  {
    key: "korbit-ai",
    label: "Korbit AI",
    classification: "ai-assisted",
    sources: {
      login: [/korbit-ai(?:\[bot\])?/i],
      coAuthor: [/korbit-ai/i],
      message: [/Generated by Korbit/i],
      prBody: [/Generated by Korbit/i],
      prBranch: [/^korbit(?:-ai)?\//i],
      detailed: [/korbit-ai(?:\[bot\])?/i],
    },
  },
];

function toClassificationPatterns(sourceKey: keyof PatternSources): PatternClassification[] {
  const patterns: PatternClassification[] = [];
  for (const mapping of AI_REVIEW_AGENT_MAPPINGS) {
    const sourcePatterns = mapping.sources[sourceKey] ?? [];
    for (const pattern of sourcePatterns) {
      patterns.push({ pattern, classification: mapping.classification });
    }
  }
  return patterns;
}

function toDetailedPatterns(sourceKey: keyof PatternSources): DetailedPatternMatch[] {
  const patterns: DetailedPatternMatch[] = [];
  for (const mapping of AI_REVIEW_AGENT_MAPPINGS) {
    const sourcePatterns = mapping.sources[sourceKey] ?? [];
    for (const pattern of sourcePatterns) {
      patterns.push({
        pattern,
        match: {
          key: mapping.key,
          label: mapping.label,
        },
      });
    }
  }
  return patterns;
}

export const AI_REVIEW_LOGIN_CLASSIFICATION_PATTERNS = toClassificationPatterns("login");
export const AI_REVIEW_COAUTHOR_CLASSIFICATION_PATTERNS = toClassificationPatterns("coAuthor");
export const AI_REVIEW_MESSAGE_CLASSIFICATION_PATTERNS = toClassificationPatterns("message");
export const AI_REVIEW_PR_BODY_CLASSIFICATION_PATTERNS = toClassificationPatterns("prBody");
export const AI_REVIEW_PR_BRANCH_CLASSIFICATION_PATTERNS = toClassificationPatterns("prBranch");
export const AI_REVIEW_DETAILED_PATTERNS = toDetailedPatterns("detailed");

export const UNKNOWN_AI_KEY = "ai-unspecified";
export const UNKNOWN_AI_LABEL = "Unknown AI Assistant";
export const UNKNOWN_AUTOMATION_KEY = "bot-unspecified";
export const UNKNOWN_AUTOMATION_LABEL = "Unknown Automation Bot";
