export type WebAlertSeverity = "info" | "success" | "warning" | "error";
export type WebAlertSurface = "banner" | "inline" | "modal" | "route-error" | "status" | "toast";
export type WebAlertAudience = "admin" | "authenticated" | "owner" | "public" | "visitor";
export type WebAlertPlacement =
  | "admin"
  | "auth"
  | "feed"
  | "global"
  | "modal"
  | "notifications"
  | "profile"
  | "repository"
  | "settings"
  | "social";
export type WebAlertPersistence = "auto-dismiss" | "dismissible" | "page" | "transient";
export type WebAlertAriaRole = "alert" | "status" | "none";

export interface WebAlertDefinition {
  id: string;
  surface: WebAlertSurface;
  severity: WebAlertSeverity;
  audience: WebAlertAudience;
  placement: WebAlertPlacement;
  title: string;
  description: string;
  actionLabel?: string;
  persistence: WebAlertPersistence;
  ariaRole: WebAlertAriaRole;
}

export const WEB_ALERTS = {
  "profile.sync.active": {
    id: "profile.sync.active",
    surface: "banner",
    severity: "info",
    audience: "owner",
    placement: "profile",
    title: "Indexing in progress",
    description: "A public repository index is currently running.",
    persistence: "page",
    ariaRole: "status",
  },
  "profile.sync.queued": {
    id: "profile.sync.queued",
    surface: "banner",
    severity: "info",
    audience: "owner",
    placement: "profile",
    title: "Queued for indexing",
    description: "One or more repositories are waiting to start indexing.",
    persistence: "page",
    ariaRole: "status",
  },
  "profile.sync.stalled": {
    id: "profile.sync.stalled",
    surface: "banner",
    severity: "warning",
    audience: "owner",
    placement: "profile",
    title: "Indexing may be stalled",
    description: "Repository indexing has not advanced recently.",
    actionLabel: "Retry indexing",
    persistence: "page",
    ariaRole: "alert",
  },
  "profile.sync.stale-public-stack": {
    id: "profile.sync.stale-public-stack",
    surface: "banner",
    severity: "warning",
    audience: "owner",
    placement: "profile",
    title: "Stack data may be stale",
    description:
      "Your public stack has not been refreshed recently. Queue a re-index to update profile packages and matches from GitHub.",
    actionLabel: "Refresh stack",
    persistence: "page",
    ariaRole: "alert",
  },
  "profile.sync.failed": {
    id: "profile.sync.failed",
    surface: "banner",
    severity: "error",
    audience: "public",
    placement: "profile",
    title: "Indexing failed",
    description: "We could not index this profile's repositories yet.",
    actionLabel: "Retry indexing",
    persistence: "page",
    ariaRole: "alert",
  },
  "profile.status.reindex-queueing": {
    id: "profile.status.reindex-queueing",
    surface: "status",
    severity: "info",
    audience: "owner",
    placement: "profile",
    title: "Queuing re-index...",
    description: "A profile re-index request is being queued.",
    persistence: "transient",
    ariaRole: "status",
  },
  "profile.status.reindex-queued": {
    id: "profile.status.reindex-queued",
    surface: "status",
    severity: "success",
    audience: "owner",
    placement: "profile",
    title: "Re-index queued. Results will refresh automatically.",
    description: "A profile re-index request was queued successfully.",
    persistence: "auto-dismiss",
    ariaRole: "status",
  },
  "profile.status.public-resync-queued": {
    id: "profile.status.public-resync-queued",
    surface: "status",
    severity: "success",
    audience: "owner",
    placement: "profile",
    title: "Public stack re-sync queued.",
    description: "A public stack re-sync request was queued successfully.",
    persistence: "auto-dismiss",
    ariaRole: "status",
  },
  "profile.status.private-sync-started": {
    id: "profile.status.private-sync-started",
    surface: "status",
    severity: "success",
    audience: "owner",
    placement: "profile",
    title: "Private aggregate sync initiated.",
    description: "Private aggregate dependency data sync has started.",
    persistence: "auto-dismiss",
    ariaRole: "status",
  },
  "profile.status.private-data-cleared": {
    id: "profile.status.private-data-cleared",
    surface: "status",
    severity: "success",
    audience: "owner",
    placement: "profile",
    title: "Private stack data cleared.",
    description: "Stored private aggregate data was cleared.",
    persistence: "auto-dismiss",
    ariaRole: "status",
  },
  "profile.status.github-app-disconnected": {
    id: "profile.status.github-app-disconnected",
    surface: "status",
    severity: "success",
    audience: "owner",
    placement: "profile",
    title: "GitHub App disconnected locally. Remove access on GitHub to revoke it fully.",
    description: "The GitHub App connection was removed locally.",
    persistence: "auto-dismiss",
    ariaRole: "status",
  },
  "profile.github-app.link-error": {
    id: "profile.github-app.link-error",
    surface: "status",
    severity: "error",
    audience: "owner",
    placement: "profile",
    title: "GitHub App installation could not be linked. Sign in and try again.",
    description: "The GitHub App installation redirect returned an error.",
    persistence: "auto-dismiss",
    ariaRole: "alert",
  },
  "profile.github-app.private-sync-started": {
    id: "profile.github-app.private-sync-started",
    surface: "status",
    severity: "success",
    audience: "owner",
    placement: "profile",
    title:
      "Private access connected. GitHub controls repository selection; aggregate dependency sync started.",
    description: "Private access was connected and private aggregate sync started.",
    persistence: "auto-dismiss",
    ariaRole: "status",
  },
  "profile.github-app.private-sync-already-running": {
    id: "profile.github-app.private-sync-already-running",
    surface: "status",
    severity: "success",
    audience: "owner",
    placement: "profile",
    title: "Private repository sync is already in progress.",
    description: "The GitHub App redirect found an existing private sync in progress.",
    persistence: "auto-dismiss",
    ariaRole: "status",
  },
  "profile.github-app.private-sync-error": {
    id: "profile.github-app.private-sync-error",
    surface: "status",
    severity: "error",
    audience: "owner",
    placement: "profile",
    title:
      "GitHub App connected, but private sync could not start. Retry private fingerprint sync.",
    description: "The GitHub App connected but private aggregate sync did not start.",
    persistence: "auto-dismiss",
    ariaRole: "alert",
  },
  "profile.github-app.connected": {
    id: "profile.github-app.connected",
    surface: "status",
    severity: "success",
    audience: "owner",
    placement: "profile",
    title:
      "GitHub App connected. Choose private repositories in GitHub, then sync the private fingerprint.",
    description: "The GitHub App was connected and awaits private repository selection.",
    persistence: "auto-dismiss",
    ariaRole: "status",
  },
  "form.owner.invalid": {
    id: "form.owner.invalid",
    surface: "inline",
    severity: "error",
    audience: "public",
    placement: "global",
    title: "Enter a valid GitHub user, organization, or GitHub URL.",
    description: "The owner lookup form received an invalid GitHub owner input.",
    persistence: "page",
    ariaRole: "alert",
  },
  "form.owner.scan-failed": {
    id: "form.owner.scan-failed",
    surface: "inline",
    severity: "error",
    audience: "public",
    placement: "global",
    title: "Failed to start scan. Please try again.",
    description: "The owner lookup scan request failed.",
    persistence: "page",
    ariaRole: "alert",
  },
  "login.recovery": {
    id: "login.recovery",
    surface: "inline",
    severity: "error",
    audience: "authenticated",
    placement: "auth",
    title: "We could not finish sign in.",
    description: "The signed-in GitHub login could not be resolved or profile claim failed.",
    actionLabel: "Try again",
    persistence: "page",
    ariaRole: "alert",
  },
  "login.sign-in-error": {
    id: "login.sign-in-error",
    surface: "inline",
    severity: "error",
    audience: "public",
    placement: "auth",
    title: "Sign in failed",
    description: "The GitHub sign-in request failed.",
    persistence: "page",
    ariaRole: "alert",
  },
  "repo.analysis.rate-limited": {
    id: "repo.analysis.rate-limited",
    surface: "inline",
    severity: "warning",
    audience: "public",
    placement: "repository",
    title: "You've analyzed 5 new repos today. Come back tomorrow!",
    description: "The repository analysis quota has been reached.",
    persistence: "page",
    ariaRole: "alert",
  },
  "repo.analysis.request-failed": {
    id: "repo.analysis.request-failed",
    surface: "inline",
    severity: "error",
    audience: "public",
    placement: "repository",
    title: "Failed to request analysis. Please try again.",
    description: "The repository analysis request failed.",
    persistence: "page",
    ariaRole: "alert",
  },
  "repo.analysis.resync-failed": {
    id: "repo.analysis.resync-failed",
    surface: "inline",
    severity: "error",
    audience: "public",
    placement: "repository",
    title: "Failed to re-sync. Please try again.",
    description: "The repository re-sync request failed.",
    persistence: "page",
    ariaRole: "alert",
  },
  "repo.sync.failed": {
    id: "repo.sync.failed",
    surface: "inline",
    severity: "error",
    audience: "public",
    placement: "repository",
    title: "Sync failed",
    description: "Repository sync failed.",
    persistence: "page",
    ariaRole: "alert",
  },
  "boundary.component": {
    id: "boundary.component",
    surface: "inline",
    severity: "error",
    audience: "public",
    placement: "global",
    title: "Something went wrong",
    description: "A component failed to render.",
    actionLabel: "Try again",
    persistence: "page",
    ariaRole: "alert",
  },
  "route.root": {
    id: "route.root",
    surface: "route-error",
    severity: "error",
    audience: "public",
    placement: "global",
    title: "Something went wrong",
    description: "An unexpected error occurred. You can try again or go back to the homepage.",
    actionLabel: "Try again",
    persistence: "page",
    ariaRole: "alert",
  },
  "route.dashboard": {
    id: "route.dashboard",
    surface: "route-error",
    severity: "error",
    audience: "public",
    placement: "profile",
    title: "Failed to load dashboard",
    description:
      "StackMatch could not reach the profile data service for this dashboard. Retry in a moment; if it keeps happening, check the app logs or service status.",
    actionLabel: "Try again",
    persistence: "page",
    ariaRole: "alert",
  },
  "route.repository": {
    id: "route.repository",
    surface: "route-error",
    severity: "error",
    audience: "public",
    placement: "repository",
    title: "Failed to load repository",
    description:
      "Something went wrong while loading this repository's dashboard. The data might be temporarily unavailable.",
    actionLabel: "Try again",
    persistence: "page",
    ariaRole: "alert",
  },
  "route.login": {
    id: "route.login",
    surface: "route-error",
    severity: "error",
    audience: "public",
    placement: "auth",
    title: "Failed to load login",
    description: "Something went wrong while loading the login experience.",
    actionLabel: "Try again",
    persistence: "page",
    ariaRole: "alert",
  },
  "route.invite": {
    id: "route.invite",
    surface: "route-error",
    severity: "error",
    audience: "public",
    placement: "auth",
    title: "Failed to redeem invite",
    description: "Something went wrong while loading this invite link.",
    actionLabel: "Try again",
    persistence: "page",
    ariaRole: "alert",
  },
  "route.docs": {
    id: "route.docs",
    surface: "route-error",
    severity: "error",
    audience: "public",
    placement: "global",
    title: "Failed to load docs",
    description: "Something went wrong while loading the documentation.",
    actionLabel: "Try again",
    persistence: "page",
    ariaRole: "alert",
  },
  "route.settings": {
    id: "route.settings",
    surface: "route-error",
    severity: "error",
    audience: "authenticated",
    placement: "settings",
    title: "Failed to load settings",
    description: "Something went wrong while loading your settings.",
    actionLabel: "Try again",
    persistence: "page",
    ariaRole: "alert",
  },
  "route.feed": {
    id: "route.feed",
    surface: "route-error",
    severity: "error",
    audience: "authenticated",
    placement: "feed",
    title: "Failed to load feed",
    description: "Something went wrong while loading your activity feed.",
    actionLabel: "Try again",
    persistence: "page",
    ariaRole: "alert",
  },
  "route.messages": {
    id: "route.messages",
    surface: "route-error",
    severity: "error",
    audience: "authenticated",
    placement: "social",
    title: "Failed to load messages",
    description: "Something went wrong while loading your conversations.",
    actionLabel: "Try again",
    persistence: "page",
    ariaRole: "alert",
  },
  "route.notifications": {
    id: "route.notifications",
    surface: "route-error",
    severity: "error",
    audience: "authenticated",
    placement: "notifications",
    title: "Failed to load notifications",
    description: "Something went wrong while loading your notifications.",
    actionLabel: "Try again",
    persistence: "page",
    ariaRole: "alert",
  },
  "route.developers": {
    id: "route.developers",
    surface: "route-error",
    severity: "error",
    audience: "public",
    placement: "global",
    title: "Failed to load developers",
    description: "Something went wrong while loading the developers directory.",
    actionLabel: "Try again",
    persistence: "page",
    ariaRole: "alert",
  },
  "route.stacks": {
    id: "route.stacks",
    surface: "route-error",
    severity: "error",
    audience: "public",
    placement: "global",
    title: "Failed to load stacks",
    description: "Something went wrong while loading the stacks directory.",
    actionLabel: "Try again",
    persistence: "page",
    ariaRole: "alert",
  },
  "route.top-stackers": {
    id: "route.top-stackers",
    surface: "route-error",
    severity: "error",
    audience: "public",
    placement: "global",
    title: "Failed to load top stackers",
    description: "Something went wrong while loading the weekly top stackers leaderboard.",
    actionLabel: "Try again",
    persistence: "page",
    ariaRole: "alert",
  },
  "route.leaderboard": {
    id: "route.leaderboard",
    surface: "route-error",
    severity: "error",
    audience: "public",
    placement: "global",
    title: "Failed to load leaderboard",
    description: "Something went wrong while loading the leaderboard.",
    actionLabel: "Try again",
    persistence: "page",
    ariaRole: "alert",
  },
  "route.stack-leaderboard": {
    id: "route.stack-leaderboard",
    surface: "route-error",
    severity: "error",
    audience: "public",
    placement: "global",
    title: "Failed to load stack leaderboard",
    description: "Something went wrong while loading the global stack leaderboard.",
    actionLabel: "Try again",
    persistence: "page",
    ariaRole: "alert",
  },
  "route.topics": {
    id: "route.topics",
    surface: "route-error",
    severity: "error",
    audience: "public",
    placement: "global",
    title: "Failed to load topics",
    description: "Something went wrong while loading the topics directory.",
    actionLabel: "Try again",
    persistence: "page",
    ariaRole: "alert",
  },
  "route.topic": {
    id: "route.topic",
    surface: "route-error",
    severity: "error",
    audience: "public",
    placement: "global",
    title: "Failed to load topic page",
    description: "Something went wrong while loading this topic page.",
    actionLabel: "Try again",
    persistence: "page",
    ariaRole: "alert",
  },
  "route.language": {
    id: "route.language",
    surface: "route-error",
    severity: "error",
    audience: "public",
    placement: "global",
    title: "Failed to load language page",
    description: "Something went wrong while loading this language page.",
    actionLabel: "Try again",
    persistence: "page",
    ariaRole: "alert",
  },
  "route.package": {
    id: "route.package",
    surface: "route-error",
    severity: "error",
    audience: "public",
    placement: "repository",
    title: "Failed to load package",
    description: "Something went wrong while loading this package page.",
    actionLabel: "Try again",
    persistence: "page",
    ariaRole: "alert",
  },
  "route.admin-moderation": {
    id: "route.admin-moderation",
    surface: "route-error",
    severity: "error",
    audience: "admin",
    placement: "admin",
    title: "Failed to load moderation",
    description: "Something went wrong while loading the moderation queue.",
    actionLabel: "Try again",
    persistence: "page",
    ariaRole: "alert",
  },
} as const satisfies Record<string, WebAlertDefinition>;

export type WebAlertId = keyof typeof WEB_ALERTS;

export function getWebAlert(id: WebAlertId): WebAlertDefinition {
  return WEB_ALERTS[id];
}

export function getWebAlertTitle(id: WebAlertId): string {
  return WEB_ALERTS[id].title;
}

export const ROUTE_ERROR_ALERT_IDS = {
  root: "route.root",
  dashboard: "route.dashboard",
  repository: "route.repository",
  login: "route.login",
  invite: "route.invite",
  docs: "route.docs",
  settings: "route.settings",
  feed: "route.feed",
  messages: "route.messages",
  notifications: "route.notifications",
  developers: "route.developers",
  stacks: "route.stacks",
  topStackers: "route.top-stackers",
  leaderboard: "route.leaderboard",
  stackLeaderboard: "route.stack-leaderboard",
  topics: "route.topics",
  topic: "route.topic",
  language: "route.language",
  package: "route.package",
  adminModeration: "route.admin-moderation",
} as const satisfies Record<string, WebAlertId>;
