import type { PRData } from "../../../github/classify_prs";
import type { AttributionClassification } from "../../attribution_mappings";
import type { CommitPayload } from "../../bot_detector";

interface CommitFixtureInput {
  message?: string;
  authorLogin?: string;
  authorType?: string;
  authorEmail?: string;
  authorName?: string;
  committerEmail?: string;
  committerName?: string;
}

function buildCommitFixture(input: CommitFixtureInput): CommitPayload {
  return {
    sha: "fixture-sha",
    commit: {
      message: input.message ?? "fix: update docs",
      author: {
        name: input.authorName ?? "Jane Doe",
        email: input.authorEmail ?? "jane@example.com",
        date: "2026-01-01T00:00:00Z",
      },
      committer: {
        name: input.committerName ?? "Jane Doe",
        email: input.committerEmail ?? "jane@example.com",
        date: "2026-01-01T00:00:00Z",
      },
    },
    author: {
      login: input.authorLogin ?? "janedoe",
      id: 1,
      type: input.authorType ?? "User",
    },
    committer: {
      login: "janedoe",
      id: 1,
      type: "User",
    },
  };
}

interface PRFixtureInput {
  login?: string;
  userType?: string;
  body?: string | null;
  labels?: string[];
  branch?: string;
}

function buildPrFixture(input: PRFixtureInput): PRData {
  return {
    number: 1,
    user: {
      login: input.login ?? "janedoe",
      type: input.userType ?? "User",
    },
    body: input.body ?? null,
    labels: (input.labels ?? []).map((name) => ({ name })),
    head: {
      ref: input.branch ?? "main",
    },
  };
}

export interface CommitClassificationFixture {
  name: string;
  commit: CommitPayload;
  expected: AttributionClassification;
}

export const COMMIT_CLASSIFICATION_FIXTURES: CommitClassificationFixture[] = [
  {
    name: "coderabbit login as bot account maps to ai-assisted",
    commit: buildCommitFixture({ authorLogin: "coderabbitai[bot]", authorType: "Bot" }),
    expected: "ai-assisted",
  },
  {
    name: "seer login as bot account maps to ai-assisted",
    commit: buildCommitFixture({ authorLogin: "seer-by-sentry[bot]", authorType: "Bot" }),
    expected: "ai-assisted",
  },
  {
    name: "sentry automation bot remains other-bot",
    commit: buildCommitFixture({ authorLogin: "sentry-bot", authorType: "Bot" }),
    expected: "other-bot",
  },
  {
    name: "co-author code rabbit marker maps to ai-assisted",
    commit: buildCommitFixture({
      message: "feat: improve checks\n\nCo-Authored-By: CodeRabbit <bot@coderabbit.ai>",
    }),
    expected: "ai-assisted",
  },
  {
    name: "regular human commit remains human",
    commit: buildCommitFixture({
      message: "fix: update styles",
      authorLogin: "david",
      authorType: "User",
    }),
    expected: "human",
  },
];

export interface PrClassificationFixture {
  name: string;
  pr: PRData;
  expected: AttributionClassification | null;
}

export const PR_CLASSIFICATION_FIXTURES: PrClassificationFixture[] = [
  {
    name: "coderabbit bot account maps to ai-assisted",
    pr: buildPrFixture({ login: "coderabbit", userType: "Bot" }),
    expected: "ai-assisted",
  },
  {
    name: "qodo branch maps to ai-assisted",
    pr: buildPrFixture({ branch: "qodo-merge/improve-ci" }),
    expected: "ai-assisted",
  },
  {
    name: "Generated by Seer marker maps to ai-assisted",
    pr: buildPrFixture({ body: "Generated by Seer" }),
    expected: "ai-assisted",
  },
  {
    name: "sentry automation bot remains other-bot",
    pr: buildPrFixture({ login: "sentry-bot", userType: "Bot" }),
    expected: "other-bot",
  },
  {
    name: "regular PR remains null",
    pr: buildPrFixture({}),
    expected: null,
  },
];

interface BreakdownFixtureCommit {
  classification: AttributionClassification;
  authorLogin?: string;
  message?: string;
  coAuthors?: string[];
}

export interface BreakdownFixture {
  name: string;
  commits: BreakdownFixtureCommit[];
  expectedAiKeys?: string[];
  expectedBotKeys?: string[];
}

export const BREAKDOWN_FIXTURES: BreakdownFixture[] = [
  {
    name: "ai review bot contributes to named AI tool bucket",
    commits: [{ classification: "ai-assisted", authorLogin: "coderabbitai[bot]" }],
    expectedAiKeys: ["coderabbit"],
  },
  {
    name: "unknown ai-assisted signal falls back to unknown bucket",
    commits: [{ classification: "ai-assisted", coAuthors: ["Jane <jane@example.com>"] }],
    expectedAiKeys: ["ai-unspecified"],
  },
  {
    name: "known automation bot contributes to named automation bucket",
    commits: [{ classification: "other-bot", authorLogin: "codecov[bot]" }],
    expectedBotKeys: ["codecov"],
  },
  {
    name: "unknown automation signal falls back to unknown bucket",
    commits: [{ classification: "other-bot", authorLogin: "" }],
    expectedBotKeys: ["bot-unspecified"],
  },
];

export function buildBreakdownCommit(input: BreakdownFixtureCommit): {
  _id: never;
  _creationTime: number;
  repoId: never;
  sha: string;
  message: string;
  authoredAt: number;
  committedAt: number;
  classification: AttributionClassification;
  authorLogin?: string;
  coAuthors?: string[];
} {
  return {
    _id: "fixture-id" as never,
    _creationTime: Date.now(),
    repoId: "repo-id" as never,
    sha: "fixture-sha",
    message: input.message ?? "test message",
    authoredAt: Date.now(),
    committedAt: Date.now(),
    classification: input.classification,
    ...(input.authorLogin !== undefined ? { authorLogin: input.authorLogin } : {}),
    ...(input.coAuthors ? { coAuthors: input.coAuthors } : {}),
  };
}
